from django.db import models


class UnprocessedData(models.Model):
    Age = models.IntegerField(null=True)
    Attrition = models.CharField(max_length=200, null=True)
    BusinessTravel = models.CharField(max_length=200, null=True)
    DailyRate = models.IntegerField(null=True)
    Department = models.CharField(max_length=200,null=True)
    DistanceFromHome = models.IntegerField(null=True)
    Education = models.IntegerField(null=True)
    EducationField = models.CharField(max_length=200, null=True)
    EmployeeCount = models.IntegerField(null=True)
    EmployeeNumber = models.IntegerField(null=True)
    EnvironmentSatisfaction = models.IntegerField(null=True)
    Gender = models.CharField(max_length=200, null=True)
    HourlyRate = models.IntegerField(null=True)
    JobInvolvement = models.IntegerField(null=True)
    JobLevel = models.IntegerField(null=True)
    JobRole = models.CharField(max_length=200, null=True)
    JobSatisfaction = models.IntegerField(null=True)
    MaritalStatus = models.CharField(max_length=200, null=True)
    MonthlyIncome = models.IntegerField(null=True)
    MonthlyRate = models.IntegerField(null=True)
    NumCompaniesWorked = models.IntegerField(null=True)
    Over18 = models.CharField(max_length=200, null=True)
    OverTime = models.CharField(max_length=200, null=True)
    PercentSalaryHike = models.IntegerField(null=True)
    PerformanceRating = models.IntegerField(null=True)
    RelationshipSatisfaction = models.IntegerField(null=True)
    StandardHours = models.IntegerField(null=True)
    StockOptionLevel = models.IntegerField(null=True)
    TotalWorkingYears = models.IntegerField(null=True)
    TrainingTimesLastYear = models.IntegerField(null=True)
    WorkLifeBalance = models.IntegerField(null=True)
    YearsAtCompany = models.IntegerField(null=True)
    YearsInCurrentRole = models.IntegerField(null=True)
    YearsSinceLastPromotion = models.IntegerField(null=True)
    YearsWithCurrManager = models.IntegerField(null=True)


class PredictFormData(models.Model):
    Algorithm = models.CharField(max_length=200)
    Age = models.IntegerField()
    BusinessTravel = models.CharField(max_length=200)
    DailyRate = models.IntegerField()
    Department = models.CharField(max_length=200)
    DistanceFromHome = models.IntegerField()
    Education = models.IntegerField()
    EducationField = models.CharField(max_length=200)
    EnvironmentSatisfaction = models.IntegerField()
    Gender = models.CharField(max_length=200)
    HourlyRate = models.IntegerField()
    JobInvolvement = models.IntegerField()
    JobLevel = models.IntegerField()
    JobRole = models.CharField(max_length=200)
    JobSatisfaction = models.IntegerField()
    MaritalStatus = models.CharField(max_length=200)
    MonthlyIncome = models.IntegerField()
    MonthlyRate = models.IntegerField()
    NumCompaniesWorked = models.IntegerField()
    OverTime = models.CharField(max_length=200)
    PercentSalaryHike = models.IntegerField()
    PerformanceRating = models.IntegerField()
    RelationshipSatisfaction = models.IntegerField()
    StandardHours = models.IntegerField()
    StockOptionLevel = models.IntegerField()
    TotalWorkingYears = models.IntegerField()
    TrainingTimesLastYear = models.IntegerField()
    WorkLifeBalance = models.IntegerField()
    YearsAtCompany = models.IntegerField()
    YearsInCurrentRole = models.IntegerField()
    YearsSinceLastPromotion = models.IntegerField()
    YearsWithCurrManager = models.IntegerField()

class ModelDetail(models.Model):
    AlgorithmName = models.CharField(max_length=200)
    ModelScoreDict = models.CharField(max_length=500)
    Date = models.DateTimeField(editable=False, auto_now_add=True)


class ModelDetailFormData(models.Model):
    algortihm = models.CharField(max_length=200)


class ModelCompareFormData(models.Model):
    algortihm1 = models.CharField(max_length=200)
    algortihm2 = models.CharField(max_length=200)

