# Generated by Django 3.0 on 2019-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attrition', models.CharField(max_length=200)),
                ('BusinessTravel', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Education', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('JobRole', models.CharField(max_length=200)),
                ('MaritalStatus', models.CharField(max_length=200)),
                ('Over18', models.CharField(max_length=200)),
                ('OverTime', models.CharField(max_length=200)),
            ],
        ),
    ]
