# Generated by Django 3.0 on 2019-12-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlgorithmName', models.CharField(max_length=200)),
                ('ModelScoreDict', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algortihm', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnprocessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Attrition', models.CharField(max_length=200)),
                ('BusinessTravel', models.CharField(max_length=200)),
                ('DailyRate', models.IntegerField()),
                ('Department', models.CharField(max_length=200)),
                ('DistanceFromHome', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('EducationField', models.CharField(max_length=200)),
                ('EmployeeCount', models.IntegerField()),
                ('EmployeeNumber', models.IntegerField()),
                ('EnvironmentSatisfaction', models.IntegerField()),
                ('Gender', models.CharField(max_length=200)),
                ('HourlyRate', models.IntegerField()),
                ('JobInvolvement', models.IntegerField()),
                ('JobLevel', models.IntegerField()),
                ('JobRole', models.CharField(max_length=200)),
                ('JobSatisfaction', models.IntegerField()),
                ('MaritalStatus', models.CharField(max_length=200)),
                ('MonthlyIncome', models.IntegerField()),
                ('MonthlyRate', models.IntegerField()),
                ('NumCompaniesWorked', models.IntegerField()),
                ('Over18', models.CharField(max_length=200)),
                ('OverTime', models.CharField(max_length=200)),
                ('PercentSalaryHike', models.IntegerField()),
                ('PerformanceRating', models.IntegerField()),
                ('RelationshipSatisfaction', models.IntegerField()),
                ('StandardHours', models.IntegerField()),
                ('StockOptionLevel', models.IntegerField()),
                ('TotalWorkingYears', models.IntegerField()),
                ('TrainingTimesLastYear', models.IntegerField()),
                ('WorkLifeBalance', models.IntegerField()),
                ('YearsAtCompany', models.IntegerField()),
                ('YearsInCurrentRole', models.IntegerField()),
                ('YearsSinceLastPromotion', models.IntegerField()),
                ('YearsWithCurrManager', models.IntegerField()),
            ],
        ),
    ]
