# Generated by Django 3.0 on 2019-12-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCompareFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algortihm1', models.CharField(max_length=200)),
                ('algortihm2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlgorithmName', models.CharField(max_length=200)),
                ('ModelScoreDict', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDetailFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algortihm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PredictFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('BusinessTravel', models.CharField(max_length=200)),
                ('DailyRate', models.IntegerField()),
                ('Department', models.CharField(max_length=200)),
                ('DistanceFromHome', models.IntegerField()),
                ('Education', models.IntegerField()),
                ('EducationField', models.CharField(max_length=200)),
                ('EnvironmentSatisfaction', models.IntegerField()),
                ('Gender', models.CharField(max_length=200)),
                ('HourlyRate', models.IntegerField()),
                ('JobInvolvement', models.IntegerField()),
                ('JobLevel', models.IntegerField()),
                ('JobRole', models.CharField(max_length=200)),
                ('JobSatisfaction', models.IntegerField()),
                ('MaritalStatus', models.CharField(max_length=200)),
                ('MonthlyIncome', models.IntegerField()),
                ('MonthlyRate', models.IntegerField()),
                ('NumCompaniesWorked', models.IntegerField()),
                ('OverTime', models.CharField(max_length=200)),
                ('PercentSalaryHike', models.IntegerField()),
                ('PerformanceRating', models.IntegerField()),
                ('RelationshipSatisfaction', models.IntegerField()),
                ('StandardHours', models.IntegerField()),
                ('StockOptionLevel', models.IntegerField()),
                ('TotalWorkingYears', models.IntegerField()),
                ('TrainingTimesLastYear', models.IntegerField()),
                ('WorkLifeBalance', models.IntegerField()),
                ('YearsAtCompany', models.IntegerField()),
                ('YearsInCurrentRole', models.IntegerField()),
                ('YearsSinceLastPromotion', models.IntegerField()),
                ('YearsWithCurrManager', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnprocessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(null=True)),
                ('Attrition', models.CharField(max_length=200, null=True)),
                ('BusinessTravel', models.CharField(max_length=200, null=True)),
                ('DailyRate', models.IntegerField(null=True)),
                ('Department', models.CharField(max_length=200, null=True)),
                ('DistanceFromHome', models.IntegerField(null=True)),
                ('Education', models.IntegerField(null=True)),
                ('EducationField', models.CharField(max_length=200, null=True)),
                ('EmployeeCount', models.IntegerField(null=True)),
                ('EmployeeNumber', models.IntegerField(null=True)),
                ('EnvironmentSatisfaction', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=200, null=True)),
                ('HourlyRate', models.IntegerField(null=True)),
                ('JobInvolvement', models.IntegerField(null=True)),
                ('JobLevel', models.IntegerField(null=True)),
                ('JobRole', models.CharField(max_length=200, null=True)),
                ('JobSatisfaction', models.IntegerField(null=True)),
                ('MaritalStatus', models.CharField(max_length=200, null=True)),
                ('MonthlyIncome', models.IntegerField(null=True)),
                ('MonthlyRate', models.IntegerField(null=True)),
                ('NumCompaniesWorked', models.IntegerField(null=True)),
                ('Over18', models.CharField(max_length=200, null=True)),
                ('OverTime', models.CharField(max_length=200, null=True)),
                ('PercentSalaryHike', models.IntegerField(null=True)),
                ('PerformanceRating', models.IntegerField(null=True)),
                ('RelationshipSatisfaction', models.IntegerField(null=True)),
                ('StandardHours', models.IntegerField(null=True)),
                ('StockOptionLevel', models.IntegerField(null=True)),
                ('TotalWorkingYears', models.IntegerField(null=True)),
                ('TrainingTimesLastYear', models.IntegerField(null=True)),
                ('WorkLifeBalance', models.IntegerField(null=True)),
                ('YearsAtCompany', models.IntegerField(null=True)),
                ('YearsInCurrentRole', models.IntegerField(null=True)),
                ('YearsSinceLastPromotion', models.IntegerField(null=True)),
                ('YearsWithCurrManager', models.IntegerField(null=True)),
            ],
        ),
    ]
