# Generated by Django 3.0 on 2019-12-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRAnalysis', '0002_auto_20191212_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unprocesseddata',
            name='Education',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unprocesseddata',
            name='EducationField',
            field=models.CharField(max_length=200),
        ),
    ]
