# Generated by Django 3.0 on 2019-12-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRAnalysis', '0003_auto_20191212_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlgorithmName', models.CharField(max_length=200)),
                ('Accuracy', models.IntegerField()),
                ('CorelationMatris', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PredictForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algortihm', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
            ],
        ),
    ]
